# Files excluded from Jekyll builds - I've probably missed some stuff
exclude:
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- jekyll-theme-dusk.gemspec
- .jekyll-metadata
- .readme
- assets/images/gallery
- _data/galleries
- _posts/
- _site

# Installed Gems - no SEO because privacy :)
#plugins:

# Jekyll settings
sass:
  style: expanded
permalink: pretty
strict_front_matter: true # not sure if this goes here

# Site settings
encoding: utf-8
title: "Dusk"
description: "A dark coloured Jekyll theme compatible with GitHub Pages, with emphasis on elegance?"

#domain: parmjot-singh.github.io
#url: https://parmjot-singh.github.io
baseurl: ""
repo: "https://github.com/parmjot-singh/jekyll-theme-dusk"
