# Files excluded from Jekyll builds - I've probably missed some stuff
exclude:
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- jekyll-theme-dusk.gemspec
- .jekyll-metadata
- .readme
- assets/images/gallery
- _data/galleries
- _posts/
- _site

# Installed Gems - no SEO because privacy :)
#plugins:

# Jekyll settings
sass:
  style: expanded
permalink: pretty
strict_front_matter: true # not sure if this goes here

# Site settings
encoding: utf-8
title: "Dusk"

#domain: parmjot-singh.github.io
#url: https://parmjot-singh.github.io
baseurl: ""
repo: "https://github.com/parmjot-singh/jekyll-theme-dusk"

# Load custom fonts
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  fonts_urls:
    # Display - Chivo Mono
    # Content - Titillium Web
    # Second link - Material Symbols
    - https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&family=Titillium+Web:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&display=swap
    - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
