name: Ruby Gem

on:
  push:
    paths:
      - jekyll-theme-dusk.gemspec
    tags:
      - "*"

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0" # Not needed with a .ruby-version file
        bundler-cache: true # runs "bundle install" and caches installed gems automatically

    - name: Build Gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Publish to GitHub Releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        GH_REPO_OWNER: ${{ github.repository_owner }}
      run: |
        repo=${GH_REPO#$GH_REPO_OWNER*}
        repo=${repo:1}

        gh release create ${{ github.ref_name }} *.gem \
            --title="$repo ${{ github.ref_name }}" \
            --generate-notes
